### ISSUE TITLE
Way of sending GALAXY_VIRTUAL_ENV to pulsar job command.sh?

### ISSUE THREAD

**Issue by dctrud** [galaxyproject/pulsar#117]
Using Galaxy 16.04 with a separate pulsar (latest dev cloned from git), jobs that depend on python packages inside the GALAXY_HOME/.venv fail:

e.g. for cufflinks:

```
Traceback (most recent call last):
  File "/project/apps/galaxy/pulsar_staging/1484/tool_files/cufflinks_wrapper.py", line 5, in <module>
    from galaxy.datatypes.util.gff_util import parse_gff_attributes, gff_attributes_to_str
  File "/project/apps/galaxy/galaxy/lib/galaxy/datatypes/util/gff_util.py", line 6, in <module>
    from bx.intervals.io import GenomicInterval, MissingFieldError, NiceReaderWrapper, ParseError, GenomicIntervalReader
ImportError: No module named bx.intervals.io
```

In the command.sh for local runner jobs `GALAXY_VIRTUAL_ENV` is set okay. For pulsar staged jobs in the pulsar staging dir `GALAXY_VIRTUAL_ENV=None` inside command.sh

I'm probably missing a config option somewhere, but is there a way of setting GALAXY_VIRTUAL_ENV that will be used by pulsar jobs?

**Comment by dctrud** [comment]
Closing this.

Eventually found I need to set the env and also run an exec to load modules in job_conf.xml on the destination.
