### ISSUE TITLE
Pulsar "AttributeError" when submitting a job

### ISSUE THREAD

**Issue by myips** [galaxyproject/pulsar#123]
Hi all,

While trying to submit a job to the cluster via Pulsar, a connection is unable to be established and this error is appearing in the paster.log file.

```
2016-10-25 18:21:16,151 DEBUG [pulsar.managers.util.drmaa][MainThread] Initializing DRMAA session from thread MainThread
Traceback (most recent call last):
  File "/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/lib/python2.7/site-packages/pulsar/web/wsgi.py", line 19, in app_factory
    webapp = init_webapp(ini_path=configuration_file, local_conf=local_conf)
  File "/usr/lib/python2.7/site-packages/pulsar/web/wsgi.py", line 25, in init_webapp
    pulsar_app = PulsarApp(**app_conf)
  File "/usr/lib/python2.7/site-packages/pulsar/core.py", line 42, in __init__
    self.__setup_managers(conf)
  File "/usr/lib/python2.7/site-packages/pulsar/core.py", line 89, in __setup_managers
    self.managers = build_managers(self, conf)
  File "/usr/lib/python2.7/site-packages/pulsar/manager_factory.py", line 47, in build_managers
    manager = _build_manager(manager_class, app, manager_name, manager_options)
  File "/usr/lib/python2.7/site-packages/pulsar/manager_factory.py", line 80, in _build_manager
    return stateful.StatefulManagerProxy(manager_class(name, app, **manager_options), **manager_options)
  File "/usr/lib/python2.7/site-packages/pulsar/managers/queued_external_drmaa.py", line 30, in __init__
    self.production = kwds.get('production', "true").lower() != "false"
AttributeError: 'bool' object has no attribute 'lower'
```

Is there an underlying issue to this error? Does anyone have any insights?

Thanks in advance!

**Comment by jmchilton** [comment]
I just did a release of pulsar which I believe fixes this particular type error - let me know if you still encounter it.

**Comment by jmchilton** [comment]
Also thanks for the detailed bug report!
