### ISSUE TITLE
Galaxy eggs? 

### ISSUE THREAD

**Issue by fikipollo** [galaxyproject/pulsar#134]
Hi again!

I'm testing some tools in Pulsar and I found a problem running _samtools_.
When running _bam_to_sam.py_ I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/pulsar/files/staging/114/tool_files/bam_to_sam.py", line 10, in <module>
    from galaxy import eggs
ImportError: cannot import name eggs
```
Reading the instructions for configuring Pulsar I found:

> Some Galaxy tool wrappers require a copy of the Galaxy codebase itself to run. Such tools will not run under Windows, but on *nix hosts the Pulsar can be configured to add the required Galaxy code a jobs PYTHON_PATH by setting GALAXY_HOME environment variable in the Pulsar’s local_env.sh file (described above).

So I've cloned the galaxy repository (git) in `/usr/local/galaxy/` and configure the _local_env.sh_  as follows:

```sh
## Place local configuration variables used by Pulsar and run.sh in here. For example

## If using the drmaa queue manager, you will need to set the DRMAA_LIBRARY_PATH variable,
## you may also need to update LD_LIBRARY_PATH for underlying library as well. 
#export DRMAA_LIBRARY_PATH=/path/to/libdrmaa.so


## If you wish to use a variety of Galaxy tools that depend on galaxy.eggs being defined, 
## set GALAXY_HOME to point to a copy of Galaxy.
export GALAXY_HOME=/usr/local/galaxy/

## Uncomment to verify GALAXY_HOME is set properly before starting the Pulsar.
export TEST_GALAXY_LIBS=1

## If using a manager that runs jobs as real users, be sure to load your Python
## environement in here as well.
# . .venv/bin/activate
```
Where `/usr/local/galaxy/` contains 
```
CITATION            contrib          cron                  external_service_types    locale           openid              run_reports.sh    scripts    test          tools
client              CONTRIBUTING.md  database              extract_dataset_parts.sh  Makefile         README.rst          run.sh            setup.cfg  test-data     tox.ini
CODE_OF_CONDUCT.md  CONTRIBUTORS.md  display_applications  lib                       manage_db.sh     requirements.txt    run_tests.sh      static     tool-data
config              create_db.sh     doc                   LICENSE.txt               manage_tools.sh  rolling_restart.sh  run_tool_shed.sh  templates  tool_list.py
```
But it doesn't work and Pulsar shows the following error when starting.

```
Sourcing file /usr/local/pulsar/scripts/../local_env.sh
Activating virtual environment /usr/local/pulsar/scripts/../.venv/bin/activate
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  ImportError: cannot import name eggs
  Failed to setup Galaxy environment properly, is GALAXY_HOME (/usr/local/galaxy/) a valid Galaxy instance.

```

I've tried also with `/usr/local/galaxy/lib/` and `/usr/local/galaxy/lib/galaxy` w/o success.
As I understand Galaxy doesn't use _eggs_ anymore so maybe I'm missing something.

Many thanks!!!

**Comment by fikipollo** [comment]
Hi again!

I managed to fix this issue so, answering myself, what I did was:

First, clone the galaxy code in local.
```bash
cd /usr/local/
git clone https://github.com/galaxyproject/galaxy.git
cd /usr/local/galaxy
git checkout master
```

Then install all the requirements for Galaxy:
```bash
cd /usr/local/pulsar/
. .venv/bin/activate
pip install -r /usr/local/galaxy/lib/galaxy/dependencies/pinned-requirements.txt  
```
_Note:_ the last python module in the requirements file "pysam==0.8.4+gx5" fails so I replaced it by "pysam==0.8.4".

Finally, I changed the _local_env.sh_ file as follows:
```sh
## Place local configuration variables used by Pulsar and run.sh in here. For example

## If using the drmaa queue manager, you will need to set the DRMAA_LIBRARY_PATH variable,
## you may also need to update LD_LIBRARY_PATH for underlying library as well. 
#export DRMAA_LIBRARY_PATH=/path/to/libdrmaa.so


## If you wish to use a variety of Galaxy tools that depend on galaxy.eggs being defined, 
## set GALAXY_HOME to point to a copy of Galaxy.
#export GALAXY_HOME=/path/to/galaxy-dist
export PYTHONPATH=${PYTHONPATH}:/usr/local/pulsar/galaxy/lib/

## Uncomment to verify GALAXY_HOME is set properly before starting the Pulsar.
export TEST_GALAXY_LIBS=1

## If using a manager that runs jobs as real users, be sure to load your Python
## environement in here as well.
# . .venv/bin/activate
``` 

and works! :dancing_men: :dancing_women::dancing_men: :dancer: :dancer:
