### ISSUE TITLE
Cannot install pulsar-galaxy-lib under Python3

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/pulsar#152]
```console
$ virtualenv -p python3.4 venv3
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in /tmp/venv3/bin/python3.4
Also creating executable in /tmp/venv3/bin/python
Installing setuptools, pip, wheel...done.
$ . venv3/bin/activate
$ pip install pulsar-galaxy-lib
Collecting pulsar-galaxy-lib
Collecting galaxy-lib (from pulsar-galaxy-lib)
  Using cached galaxy_lib-17.9.10-py2.py3-none-any.whl
Collecting pyyaml (from pulsar-galaxy-lib)
Collecting webob (from pulsar-galaxy-lib)
  Downloading WebOb-1.7.4-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 3.5MB/s 
Collecting six (from pulsar-galaxy-lib)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting psutil (from pulsar-galaxy-lib)
  Downloading psutil-5.4.3.tar.gz (412kB)
    100% |████████████████████████████████| 419kB 2.3MB/s 
Collecting docutils (from galaxy-lib->pulsar-galaxy-lib)
  Using cached docutils-0.14-py3-none-any.whl
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... done
Successfully built psutil
Installing collected packages: docutils, pyyaml, six, galaxy-lib, webob, psutil, pulsar-galaxy-lib
Exception:
Traceback (most recent call last):
  File "/tmp/venv3/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/venv3/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/tmp/venv3/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/tmp/venv3/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/tmp/venv3/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/tmp/venv3/lib/python3.4/site-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: pulsar-galaxy-lib .dist-info directory not found
```

This is a blocker for running Galaxy under Python3.

**Comment by jmchilton** [comment]
I tried something and now the version indicators are right - but PyPI still says the wheel is Python 2 :(.

**Comment by nsoranzo** [comment]
@jmchilton That should be fixed by https://github.com/galaxyproject/pulsar/pull/156

**Comment by jmchilton** [comment]
Should be fixed now - thanks!

**Comment by nsoranzo** [comment]
Thanks @jmchilton!
