### ISSUE TITLE
assign_ids: uuid produces an IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/pulsar#194]
I have set assign_ids: uuid in the app.yml file and the result has been an IOError: [Errno 2] No such file or directory:

```
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: 2019-06-17 14:36:41,898 ERROR [pulsar.messaging.bind_amqp][consume-setup-pyamqp://galaxy_freiburg:********@proxy.internal.galaxyproject.eu:5671//pulsar/galaxy_freiburg?ssl=1] Failed to setup job 161 obtained via message queue.
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: Traceback (most recent call last):
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/messaging/bind_amqp.py", line 117, in __process_setup_message
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: manager_endpoint_util.submit_job(manager, body)
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/manager_endpoint_util.py", line 102, in submit_job
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: manager.preprocess_and_launch(job_id, launch_config)
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 85, in preprocess_and_launch
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: self._persist_launch_config(job_id, launch_config)
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 76, in _persist_launch_config
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: job_directory.store_metadata("launch_config", launch_config)
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/__init__.py", line 330, in store_metadata
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: self.write_file(metadata_name, json.dumps(metadata_value))
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/__init__.py", line 256, in write_file
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: job_file = open(path, 'wb')
Jun 17 14:36:41 vgcn-central-manager.usegalaxy.eu.novalocal pulsar[333945]: IOError: [Errno 2] No such file or directory: u'/data/share/staging/161/launch_config'
```

/data/share/staging/161 should be /data/share/staging/e555002620574d77ad3685ffb12645aa

**Comment by jmchilton** [comment]
Are you using ``__PULSAR_JOBS_DIRECTORY__`` - do you have to be using that option?

**Comment by gmauro** [comment]
No, I'm not using that option.

**Comment by hexylena** [comment]
Probably solved with above comment. @gmauro reopen if not :)

**Comment by hexylena** [comment]
rediscovered this today, `assign_ids: uuid` causes the job to be marked as `lost` immediately even though it's running and succeeding on the DRM.

my job conf has 

```
<destination id="remote_localhost" runner="pulsar">                             
    <param id="url">https://p9.src-sensitive-i.src.surf-hosted.nl</param>       
    <param id="dependency_resolution">remote</param>                            
    <param id="private_token">...</param>                             
    <param id="manager">_default_</param>                                       
</destination>                                                                  
```

and every single job fails. I've dug through https://github.com/galaxyproject/pulsar/pull/196 and https://github.com/galaxyproject/galaxy/pull/8718 but neither seem to fix it, it's not clear if something needs to be changed on the galaxy side, but, I'd expect nothing to change on the galaxy side, pulsar is just actively losing jobs if it's setup with uuid (as far as i can tell. Maybe my pulsar is misconfigured but that's not being surfaced in a way I can see)

**Comment by natefoo** [comment]
I am also encountering this with a relatively vanilla MQ instance and `assign_ids: uuid`.

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/galaxy/pull/8718 I think fixed this.
