### ISSUE TITLE
AttributeError: 'ToolRequirement' object has no attribute 'get' with latest master

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/pulsar#204]
Pushing it here that I don't loose it in the hope I can fix it over the weekend.

It seems that latest pulsar is pulling `galaxy_tool_util` in but passsing a `ToolRequirement` object into a function that expects a dict().

```
> Traceback (most recent call last):
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 127, in _handling_of_preprocessing_state
> **launch_kwds
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/queued_condor.py", line 36, in launch
> setup_params=setup_params
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/directory.py", line 120, in _setup_job_file
> command_line = self._expand_command_line(command_line, dependencies_description, job_directory=self.job_directory(job_id).job_directory)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/__init__.py", line 197, in _expand_command_line
> job_directory=job_directory,
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 181, in dependency_shell_commands
> requirements_to_dependencies = self.requirements_to_dependencies(requirements, **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 191, in requirements_to_dependencies
> requirement_to_dependency = self._requirements_to_dependencies_dict(requirements, **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 246, in _requirements_to_dependencies_dict
> **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/resolvers/conda.py", line 211, in resolve_all
> expanded_requirements = ToolRequirements([self._expand_requirement(r) for r in requirements])
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/requirements.py", line 109, in __init__
> self.tool_requirements = OrderedSet([r if isinstance(r, ToolRequirement) else ToolRequirement.from_dict(r) for r in tool_requirements])
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/requirements.py", line 42, in from_dict
> version = dict.get("version", None) ##dict.version or None
> AttributeError: 'ToolRequirement' object has no attribute 'get'
> 2019-08-23 16:23:13,234 ERROR [pulsar.managers.stateful][[manager=production]-[action=preprocess]-[job=5884047]] Failed job preprocessing for job 5884047:
> Traceback (most recent call last):
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 127, in _handling_of_preprocessing_state
> **launch_kwds
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/queued_condor.py", line 36, in launch
> setup_params=setup_params
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/directory.py", line 120, in _setup_job_file
> command_line = self._expand_command_line(command_line, dependencies_description, job_directory=self.job_directory(job_id).job_directory)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/pulsar/managers/base/__init__.py", line 197, in _expand_command_line
> job_directory=job_directory,
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 181, in dependency_shell_commands
> requirements_to_dependencies = self.requirements_to_dependencies(requirements, **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 191, in requirements_to_dependencies
> requirement_to_dependency = self._requirements_to_dependencies_dict(requirements, **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 246, in _requirements_to_dependencies_dict
> **kwds)
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/resolvers/conda.py", line 211, in resolve_all
> expanded_requirements = ToolRequirements([self._expand_requirement(r) for r in requirements])
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/requirements.py", line 109, in __init__
> self.tool_requirements = OrderedSet([r if isinstance(r, ToolRequirement) else ToolRequirement.from_dict(r) for r in tool_requirements])
> File "/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/tool_util/deps/requirements.py", line 42, in from_dict
> version = dict.get("version", None) ##dict.version or None
> AttributeError: 'ToolRequirement' object has no attribute 'get'
```

**Comment by bgruening** [comment]
Mh, Ok, I will try again with a new release and open a new one. Thanks!
