### ISSUE TITLE
Problems with UTF-8 streams under Windows.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/pulsar#51]
Multiple reports - one in galaxy-dev (http://dev.list.galaxyproject.org/Problem-with-LWR-input-size-limitation-td4666038.html) and galaxy-proteomics ().

```
Exception happened during processing of request from ('192.168.56.1', 42932)
Traceback (most recent call last):
  File "C:\python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "C:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\python27\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "C:\python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "C:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "C:\python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "E:\lwr\lwr\web\framework.py", line 37, in __call__
    return controller(environ, start_response, **request_args)
  File "E:\lwr\lwr\web\framework.py", line 141, in controller_replacement
    resp = self.__build_response(result)
  File "E:\lwr\lwr\web\framework.py", line 129, in __build_response
    resp = Response(body=self.body(result))
  File "E:\lwr\lwr\web\framework.py", line 155, in body
    body = dumps(result)
  File "C:\python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc6 in position 10: invalid continuation byte
----------------------------------------
```

**Comment by jmchilton** [comment]
Sounds like switch the Pulsar fixes this (probably better stream handling to support Python 3).

**Comment by erasche** [comment]
You know... if we rewrote pulsar in golang we could cross compile for [absolutely everyone](https://github.com/docker-library/golang/blob/3427e88341de17a4d8921b859180a2649e1ab96e/1.4/cross/Dockerfile#L7) (not to push a language few galaxy people write)
