### ISSUE TITLE
Paster problems under some scenarios.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/pulsar#59]
https://biostar.usegalaxy.org/p/11337/

**Comment by dctrud** [comment]
See same thing if I try `./run.sh --mode paster`. Running `./run.sh` alone will start up in uwsgi mode without any errors. This is on RHEL 6.6 with a venv originating from a pyenv python 2.7.8. This setup working fine for galaxy itself.

````
(.venv)-bash-4.1$ ./run.sh --mode paster
Traceback (most recent call last):
  File "/project/apps/galaxy/pulsar/.venv/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/paste/script/command.py", line 93, in run
    commands = get_commands()
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/paste/script/command.py", line 135, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/paste/script/pluginlib.py", line 82, in resolve_plugins
    pkg_resources.require(plugin)
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 940, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 813, in resolve
    if dist is None or (dist not in req and replace_conflicting):
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2952, in __contains__
    item = item.version
  File "/project/apps/galaxy/pulsar/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2562, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file", wsgi-path [unknown version] (/project/apps/galaxy/pulsar))
````

**Comment by jmchilton** [comment]
@dctrud - thanks for weighing in on this. Good to know it wasn't just Windows - made it easier to address the problem when I don't have to reboot :). I was able to reproduce this eventually - but I wasn't able to figure out precisely why my development copy didn't have this problem but a fresh clone did.

At any rate I suspect the terrible hack 601972d should fix things - let me know if the problem persists.

**Comment by dctrud** [comment]
Yes, 601972d does fix for `./run.sh --mode=paster` on my setup.

Cheers!

**Comment by jmchilton** [comment]
Awesome - thanks! P.S. Will try to catch up on the ``copy`` issue tonight.
