### ISSUE TITLE
pip-install missing galaxy.util.pastescript

### ISSUE THREAD

**Issue by erasche** [galaxyproject/pulsar#91]
```
(env)hxr@leda:~/work/pulsar$ docker run -it --entrypoint=/bin/bash python:2.7
root@b0be51845ff2:/# pip install pulsar-app
root@b0be51845ff2:/#     mkdir pulsar-mq-config
root@b0be51845ff2:/#     cd pulsar-mq-config
root@b0be51845ff2:/pulsar-mq-config#     pulsar-config --mq
root@b0be51845ff2:/pulsar-mq-config#     pulsar-main
No handlers could be found for logger "pulsar.main"
Traceback (most recent call last):
  File "/usr/local/bin/pulsar-main", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 325, in main
    app_loop(args, log)
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 122, in app_loop
    pulsar_app = _app(args, log)
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 146, in _app
    log=log,
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 113, in load_pulsar_app
    config = config_builder.load()
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 242, in load
    app_name=self.app_name
  File "/usr/local/lib/python2.7/site-packages/pulsar/main.py", line 172, in load_app_configuration
    from galaxy.util.pastescript.loadwsgi import ConfigLoader
ImportError: No module named pastescript.loadwsgi
```

And indeed the package is nowhere to be found

```
/usr/local/lib/python2.7/site-packages/galaxy/util
/usr/local/lib/python2.7/site-packages/galaxy/util/odict.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/plugin_config.py
/usr/local/lib/python2.7/site-packages/galaxy/util/submodules.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/submodules.py
/usr/local/lib/python2.7/site-packages/galaxy/util/__init__.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/bunch.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/plugin_config.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/bunch.py
/usr/local/lib/python2.7/site-packages/galaxy/util/sleeper.pyc
/usr/local/lib/python2.7/site-packages/galaxy/util/sleeper.py
/usr/local/lib/python2.7/site-packages/galaxy/util/__init__.py
/usr/local/lib/python2.7/site-packages/galaxy/util/odict.py
/usr/local/lib/python2.7/site-packages/galaxy/util/directory_hash.py
/usr/local/lib/python2.7/site-packages/galaxy/util/directory_hash.pyc
```

**Comment by erasche** [comment]
Importing a copy of the galaxy directory to the mounted volume:

```
root@338909c933e1:/pulsar# PYTHONPATH="." pulsar --mode webless
Sourcing file ./local_env.sh
Starting pulsar with command [pulsar-main]
No handlers could be found for logger "pulsar.main"
Traceback (most recent call last):
  File "/usr/local/bin/pulsar-main", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 325, in main
    app_loop(args, log)
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 122, in app_loop
    pulsar_app = _app(args, log)
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 146, in _app
    log=log,
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 113, in load_pulsar_app
    config = config_builder.load()
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 242, in load
    app_name=self.app_name
  File "/usr/local/lib/python2.7/dist-packages/pulsar/main.py", line 173, in load_app_configuration
    local_conf = ConfigLoader(ini_path).app_context(app_name).config()
  File "/pulsar/galaxy/util/pastescript/loadwsgi.py", line 465, in app_context
    APP, name=name, global_conf=global_conf)
  File "/pulsar/galaxy/util/pastescript/loadwsgi.py", line 511, in get_context
    object_type, name=name)
  File "/pulsar/galaxy/util/pastescript/loadwsgi.py", line 690, in find_config_section
    self.filename))
LookupError: No section 'main' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /pulsar/server.ini
```

**Comment by erasche** [comment]
Okay, I must be doing something very wrong. Even happens on the 0.5.0 release of pulsar:

- pulsar-config works, instructs me to run "pulsar"

```
    from six.moves import UserDict
ImportError: cannot import name UserDict
```

pulsar-main prints

```
    from galaxy.util.pastescript.loadwsgi import ConfigLoader
ImportError: No module named pastescript.loadwsgi
```

and pulsar-run prints

```
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

No rush, but I'm a bit stymied
